### ISSUE TITLE
关于提示位置和更多地方应用的问题

### ISSUE THREAD

**Issue by goodDOS** [sy-records/wp-baidu-textcensor#1]
![QQ截图20200317220745](https://user-images.githubusercontent.com/16776856/76925729-5c2e7680-6915-11ea-92f0-a0dfae3d2088.png)
返回的提示位置有点迷，建议给个代码让用户自定义显示位置。

或者改为弹窗提示：
![QQ图片20200317220615](https://user-images.githubusercontent.com/16776856/76925748-736d6400-6915-11ea-97ed-378b9942a102.png)

还有，
如果能让用户自己填写钩子什么的代码实现多个第三方插件内容审核就更棒啦（伸手

**Comment by sy-records** [comment]
提示内容使用的WordPress自带的`wp_die`方法，显示内容和主题有关，比如我博客就是对于的alert弹窗。修改 `wp-baidu-textcensor.php`文件的第[173](https://github.com/sy-records/wp-baidu-textcensor/blob/master/wp-baidu-textcensor.php#L173) 行就可以了

**Comment by sy-records** [comment]
多个第三方插件内容审核是什么意思？不使用百度云的api，使用其他的api吗？

**Comment by sy-records** [comment]
哦 应该是开启了好几个插件来审核内容，插件应该都使用的钩子，添加一个和多个没什么区别，应该都会执行到

**Comment by goodDOS** [comment]
嘛，就是如果使用第三方的论坛插件，也需要审核。所以不知通过填写论坛的钩子来审核是否可行（不太懂代码

**Comment by goodDOS** [comment]
我启用审核了呀，你试试用传统国骂。

**Comment by goodDOS** [comment]
谢谢作者解答😄

**Comment by sy-records** [comment]
你人机验证的插件有问题
